# Enable the Sponsor button on GitHub. Fill in the handle you want to use, then
# uncomment the line. See https://docs.github.com/sponsors.
github: [SimonErich]
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
# custom: ["https://fluvie.dev/sponsor"]
