import 'package:fluvie/src/rendering/encoding/audio_graph_nodes.dart';

/// A silent stereo track of a fixed duration, generated by FFmpeg's
/// `anullsrc` lavfi source.
///
/// Test fixture for the encoder's audio seam: it proves the argument
/// builder's non-empty audio path (inputs, `-map` routing, `-shortest`)
/// without any real audio engine. Real [FfmpegAudioNode]s land in Phase 13.1.
final class SilentTrackNode implements FfmpegAudioNode {
  /// Creates [durationSeconds] of silence (48 kHz stereo).
  SilentTrackNode(this.durationSeconds);

  /// How long the silent track runs, in seconds.
  final num durationSeconds;

  @override
  List<String> inputArgs() => [
    '-f',
    'lavfi',
    '-t',
    '$durationSeconds',
    '-i',
    'anullsrc=r=48000:cl=stereo',
  ];

  @override
  String mapSpecifier(int inputIndex) => '$inputIndex:a';

  // Chain-less: the fixture proves the legacy direct-`-map` path, not the real
  // `-filter_complex` mix that the audio layer's nodes drive (decision D-Mix).
  @override
  String? filterChain({required int inputIndex, required String label}) => null;
}
