import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:fluvie_editor/fluvie_editor.dart' show editorCommands;

/// The shortcuts reference is generated by hand but pinned by machine: every
/// registry binding must appear in the docs table with the exact chord the
/// menus print. A new or changed binding fails here until the page follows.
void main() {
  test('the shortcuts page lists every registry binding', () {
    final page = File('../../documentation/editor/editor-shortcuts.md');
    expect(
      page.existsSync(),
      isTrue,
      reason: 'documentation/editor/editor-shortcuts.md is the shortcuts reference',
    );
    final text = page.readAsStringSync();
    for (final entry in editorCommands) {
      final shortcut = entry.shortcut;
      if (shortcut == null) continue;
      // The tests run on the Linux baseline, so the hint spells Ctrl; the
      // page notes that Cmd replaces Ctrl on macOS.
      expect(
        text,
        contains('`${shortcut.hint}`'),
        reason: '${entry.id} binds ${shortcut.hint}',
      );
      expect(text, contains(entry.title), reason: '${entry.id} is titled ${entry.title}');
    }
  });

  test('the tool letters and the palette chord are on the page', () {
    final text = File('../../documentation/editor/editor-shortcuts.md').readAsStringSync();
    for (final chord in const ['`V`', '`H`', '`T`', '`R`', '`O`', '`L`', '`A`', '`M`', 'Ctrl+K']) {
      expect(text, contains(chord));
    }
  });
}
