# Fluvie marketing landing (fluvie.dev): a single static page behind nginx.
#
# Build from the repo root so the logo is in the build context:
#   docker build -f deploy/landing.Dockerfile -t fluvie-web .
FROM nginx:alpine
COPY web/landing/index.html /usr/share/nginx/html/index.html
# Brand logos: normal (light backgrounds) and inverted (dark hero/footer).
COPY web/landing/fluvie_logo.svg /usr/share/nginx/html/fluvie_logo.svg
COPY web/landing/fluvie_logo_inverted.svg /usr/share/nginx/html/fluvie_logo_inverted.svg
# Social/OG share card.
COPY web/landing/og.png /usr/share/nginx/html/og.png
# Example gallery clips (generated by tool/web/regenerate_gallery.sh).
COPY web/landing/media/ /usr/share/nginx/html/media/
EXPOSE 80
