import 'dart:io';

/// Copies the canonical workspace policy into publishable packages so their
/// analysis and formatter configuration also works outside this checkout.
/// Run with `--write` after editing the root policy; CI uses `--check`.
void main(List<String> arguments) {
  if (arguments.length != 1 || !const ['--check', '--write'].contains(arguments.single)) {
    stderr.writeln('Usage: dart tool/sync_package_analysis.dart --check|--write');
    exitCode = 64;
    return;
  }
  final write = arguments.single == '--write';
  final policy = File('analysis_options.yaml').readAsStringSync();
  final baseDependency = RegExp(
    r'^  very_good_analysis: .+$',
    multiLine: true,
  ).firstMatch(File('pubspec.yaml').readAsStringSync())!.group(0)!;
  final generated =
      '# Generated by tool/sync_package_analysis.dart. Do not edit.\n'
      '# Source of truth: the workspace root analysis_options.yaml.\n\n$policy';
  var checked = 0;
  for (final directory in Directory('packages').listSync().whereType<Directory>()) {
    final manifest = File('${directory.path}/pubspec.yaml');
    if (!manifest.existsSync()) continue;
    final pubspec = manifest.readAsStringSync();
    if (RegExp(r'''^publish_to:\s*['"]?none['"]?\s*$''', multiLine: true).hasMatch(pubspec)) {
      continue;
    }
    if (!pubspec.split('\n').contains(baseDependency)) {
      stderr.writeln('${manifest.path} must declare $baseDependency in dev_dependencies.');
      exitCode = 1;
    }
    final options = File('${directory.path}/analysis_options.yaml');
    if (!options.readAsStringSync().contains('include: analysis_options.shared.yaml')) {
      stderr.writeln('${options.path} must include analysis_options.shared.yaml.');
      exitCode = 1;
    }
    final target = File('${directory.path}/analysis_options.shared.yaml');
    if (write) {
      target.writeAsStringSync(generated);
    } else if (!target.existsSync() || target.readAsStringSync() != generated) {
      stderr.writeln('${target.path} is stale. Run dart tool/sync_package_analysis.dart --write.');
      exitCode = 1;
    }
    checked++;
  }
  stdout.writeln('${write ? 'Wrote' : 'Checked'} $checked publishable package analysis policies.');
}
