/// The capture harness `fluvie init` writes to `test/render/`.
///
/// It is self-contained and uses only the public barrels — the authoring
/// surface plus `package:fluvie/rendering.dart` for the capture pipeline — so
/// `fluvie render <key>` works in any project that has this file, with no
/// dependency on the Fluvie example app. It covers media-less compositions
/// (text, shapes, charts, gradients); add an `ImageResolverScope` for `Image`
/// or `Clip` media.
library;

/// One renderable composition for the generated harness registry.
typedef HarnessComposition = ({String key, String function, String libPath});

/// The source of `test/render/capture_harness_test.dart` for [packageName],
/// registering every composition in [compositions] (the `fluvie render` keys).
String captureHarnessSource({
  required String packageName,
  required List<HarnessComposition> compositions,
}) {
  final imports = [
    for (final c in compositions) "import 'package:$packageName/${c.libPath}';",
  ].join('\n');
  final registry = [
    for (final c in compositions) "  '${c.key}': ${c.function},",
  ].join('\n');
  return _harness.replaceFirst('{{IMPORTS}}', imports).replaceFirst('{{REGISTRY}}', registry);
}

const String _harness = r'''
// GENERATED by `fluvie init`: the capture harness the fluvie CLI drives via
// `flutter test --dart-define`. A plain `flutter test` run skips the render, so
// this file stays green in your normal suite. It uses only the public Fluvie
// API. Re-run `fluvie init` to regenerate, or edit the registry below by hand.

import 'dart:io';

import 'package:alchemist/alchemist.dart' show loadFonts;
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:fluvie/fluvie.dart';
import 'package:fluvie/rendering.dart';

{{IMPORTS}}

/// Every composition this project can render, keyed for `fluvie render <key>`.
/// Add an import above and an entry here to register another video.
final Map<String, Video Function()> compositions = {
{{REGISTRY}}
};

const String _key = String.fromEnvironment('FLUVIE_RENDER_KEY');
const String _outDir = String.fromEnvironment('FLUVIE_RENDER_OUT_DIR');
const String _frames = String.fromEnvironment('FLUVIE_RENDER_FRAMES');
const String _noCache = String.fromEnvironment('FLUVIE_RENDER_NO_CACHE');
const String _list = String.fromEnvironment('FLUVIE_RENDER_LIST');
const String _format = String.fromEnvironment('FLUVIE_RENDER_FORMAT');

void main() {
  testWidgets('the capture harness renders the keyed composition', (tester) async {
    // `fluvie list` mode: print the keys behind the marker the CLI parses.
    if (bool.tryParse(_list) ?? false) {
      stdout.writeln('fluvie-keys: ${compositions.keys.join(', ')}');
      return;
    }
    // A plain `flutter test` run (no define) is a no-op, so the suite stays green.
    if (_key.isEmpty) {
      markTestSkipped('No FLUVIE_RENDER_KEY: this harness only runs under `fluvie render`.');
      return;
    }
    final build = compositions[_key];
    if (build == null) {
      // The marker the CLI parses for a friendly unknown-key error.
      stdout.writeln(
        'fluvie-unknown-key: Unknown render key "$_key". '
        'Known keys: ${compositions.keys.join(', ')}',
      );
      fail('Unknown render key "$_key".');
    }
    expect(_outDir, isNotEmpty, reason: 'FLUVIE_RENDER_OUT_DIR must point at the CLI sandbox');

    // Load the real bundled fonts; otherwise `flutter test` draws text with the
    // Ahem font (every glyph a filled box).
    await loadFonts();

    final video = build();
    final width = video.width;
    final height = video.height;
    tester.view.physicalSize = Size(width.toDouble(), height.toDouble());
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);

    final controller = RenderController();
    final boundaryKey = GlobalKey();
    await tester.pumpWidget(
      RenderModeContext(
        mode: RenderMode.capture,
        child: RenderControllerScope(
          controller: controller,
          child: RepaintBoundary(
            key: boundaryKey,
            child: DefaultTextStyle.merge(
              style: const TextStyle(fontFamily: 'Roboto'),
              child: Directionality(textDirection: TextDirection.ltr, child: video),
            ),
          ),
        ),
      ),
    );

    final noCache = bool.tryParse(_noCache) ?? false;
    final service = RenderService(
      capture: const RepaintBoundaryCaptureService(),
      cache: FrameCache(FrameCache.defaultRoot()),
      media: const NoMediaResolver(),
    );
    await tester.runAsync(() async {
      await service.captureToDirectory(
        config: RenderConfig(
          width: width,
          height: height,
          fps: video.fps,
          frameCount: _frames.isEmpty ? video.totalFrames : int.parse(_frames),
          cacheEnabled: !noCache,
        ),
        outDir: Directory(_outDir),
        pump: (frame) async {
          controller.seek(frame);
          await tester.pump();
        },
        boundaryKey: boundaryKey,
        compositionKey: _key,
        export: _exportFor(_format),
      );
    });
  }, timeout: Timeout.none);
}

/// Maps a `--format` define to an `Export` (null is the mp4 default).
Export? _exportFor(String format) => switch (format) {
  '' || 'mp4' => null,
  'gif' => const Export.gif(),
  'imageSequence' => const Export.imageSequence(),
  'transparent' => const Export.transparent(),
  _ => throw ArgumentError.value(format, 'format', 'unknown export format'),
};
''';
