import 'package:fluvie_cli/src/templates/ai_evidence_template.dart';
import 'package:fluvie_cli/src/templates/ai_prompt_template.dart';
import 'package:fluvie_cli/src/templates/ai_trace_template.dart';

/// The static WidgetTester adapter for the package-owned render engine.
/// No rendering policy or font implementation is copied into consumer projects.
String fileHarnessSource({
  required String targetImport,
  String entry = 'build',
  Duration? timeout,
  String? rendererImport,
  String rendererEntry = 'buildRenderer',
  bool asynchronous = false,
  bool worker = false,
}) {
  final testTimeout = timeout == null
      ? 'Timeout.none'
      : 'const Timeout(Duration(seconds: ${timeout.inSeconds}))';
  return '''
// GENERATED by Fluvie. This cached adapter statically imports your composition.
import 'dart:io';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
${worker ? '' : "import 'package:fluvie/fluvie.dart' show Video;"}
import 'package:fluvie/rendering.dart';
import ${_literal(targetImport)} as target;
${rendererImport == null ? '' : 'import ${_literal(rendererImport)} as custom;'}

void main() {
  testWidgets('fluvie render', (tester) async {
    await HttpOverrides.runWithHttpOverrides(() async {
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
    ${worker ? '''
    await runFluvieWorker(
      videoFactory: target.$entry,
      mailbox: Directory(const String.fromEnvironment('FLUVIE_WORKER_MAILBOX')),
      hostFactory: () => RenderHostContext(
        pumpWidget: tester.pumpWidget,
        pumpFrame: () => tester.pump(),
        setViewSize: (width, height) {
          tester.view.physicalSize = Size(width.toDouble(), height.toDouble());
          tester.view.devicePixelRatio = 1;
        },
        runAsync: tester.runAsync,
      ),
    );
    ''' : '''
    final video = ${asynchronous ? 'await tester.runAsync<Video>(() => target.$entry())' : 'target.$entry()'};
    ${asynchronous ? "if (video == null) throw StateError('The video builder returned no Video.');" : ''}
    if (const String.fromEnvironment('FLUVIE_OPERATION') == 'author') return;
    await runFluvieRender(
      video: video,
      videoFactory: target.$entry,
      host: RenderHostContext(
        pumpWidget: tester.pumpWidget,
        pumpFrame: () => tester.pump(),
        setViewSize: (width, height) {
          tester.view.physicalSize = Size(width.toDouble(), height.toDouble());
          tester.view.devicePixelRatio = 1;
        },
        runAsync: tester.runAsync,
      ),
      ${rendererImport == null ? '' : 'rendererFactory: custom.$rendererEntry,'}
    );
    '''}
    }, _RenderHttpOverrides());
  }, timeout: $testTimeout);
}

// Flutter's test binding mocks HTTP as status 400. Rendering and authoring
// need real media/provider HTTP within this adapter's zone, never globally.
final class _RenderHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) => super.createHttpClient(context);
}
''';
}

String _literal(String text) =>
    "'${text.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

/// A spec builder shared by spec rendering and built-in authoring.
String specInputSource({bool author = false}) =>
    '''
import 'dart:convert';
import 'dart:io';
import 'package:fluvie/fluvie.dart';
${author ? "import 'package:fluvie_ai/fluvie_ai.dart';" : ''}

Future<Video> build() async {
  ${author ? """
$aiPromptInputSource
  const basePath = String.fromEnvironment('FLUVIE_AI_BASE_SPEC');
  const specOut = String.fromEnvironment('FLUVIE_RENDER_SPEC_OUT');
  const provider = String.fromEnvironment('FLUVIE_AI_PROVIDER');
  final env = <String, String>{...Platform.environment, if (provider.isNotEmpty) 'FLUVIE_AI_PROVIDER': provider};
  final base = basePath.isEmpty ? null : VideoSpec.fromJson(jsonDecode(await File(basePath).readAsString()) as Map<String, Object?>);
  final baseClient = aiClientFromEnv(env);
$aiTraceClientSource
  const contextPath = String.fromEnvironment('FLUVIE_AI_CONTEXT_FILE');
  final context = contextPath.isEmpty ? '' : await File(contextPath).readAsString();
$aiEvidenceInput
  final spec = await LlmVideoAuthorService(client: client).author(context.isEmpty ? prompt : '\$prompt\\n\\n\$context', base: base, evidenceImages: evidenceImages);
  final file = File(specOut); await file.parent.create(recursive: true);
  await file.writeAsString(const JsonEncoder.withIndent('  ').convert(spec.toJson()));
  return spec.build();
""" : """
  const specPath = String.fromEnvironment('FLUVIE_RENDER_SPEC');
  final json = jsonDecode(await File(specPath).readAsString()) as Map<String, Object?>;
  assertNoUnknownSpecProps(json);
  return VideoSpec.fromJson(json).build();
"""}
}
''';
