/// The capture harness the CLI generates per render.
///
/// It is regenerated on every render and never committed, so it cannot drift
/// from the CLI that writes it. The whole render is fluvie's `renderVideo`; this
/// text supplies only what a `flutter_test` host alone can (the pump, the view,
/// a real event loop) and reads the `--dart-define`s the CLI passes.
library;

/// The Dart source of a generated capture harness.
///
/// [targetImport] is the import URI of the file declaring the composition,
/// relative to the generated harness (or a `package:` URI when the target lives
/// under `lib/`). [entry] is the top-level function returning the `Video`
/// (`build` by convention). [timeout] bounds the test: `null` means
/// `Timeout.none`, which a trusted local render wants; an untrusted render
/// passes a duration so a runaway `build()` is killed by `flutter test`.
///
/// A pure function (no IO), so the template is unit-tested without a Flutter
/// toolchain.
String fileHarnessSource({
  required String targetImport,
  String entry = 'build',
  Duration? timeout,
}) {
  final timeoutArg = timeout == null
      ? 'Timeout.none'
      : 'const Timeout(Duration(seconds: ${timeout.inSeconds}))';
  return '''
// GENERATED by the fluvie CLI. Do not edit: it is rewritten on every render.
//
// It statically imports the composition so `flutter test` JIT-compiles it, then
// drives fluvie's shared capture pipeline.

import 'dart:io';

import 'package:alchemist/alchemist.dart' show loadFonts;
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:fluvie/fluvie.dart';
import 'package:fluvie/rendering.dart';

import '$targetImport' as target;

const String _key = String.fromEnvironment('FLUVIE_RENDER_KEY');
const String _outDir = String.fromEnvironment('FLUVIE_RENDER_OUT_DIR');
const String _frames = String.fromEnvironment('FLUVIE_RENDER_FRAMES');
const String _noCache = String.fromEnvironment('FLUVIE_RENDER_NO_CACHE');
const String _aspect = String.fromEnvironment('FLUVIE_RENDER_ASPECT');
const String _quality = String.fromEnvironment('FLUVIE_RENDER_QUALITY');
const String _format = String.fromEnvironment('FLUVIE_RENDER_FORMAT');
const String _poster = String.fromEnvironment('FLUVIE_RENDER_POSTER');

void main() {
  testWidgets('fluvie render', (tester) async {
    expect(_outDir, isNotEmpty, reason: 'FLUVIE_RENDER_OUT_DIR must point at the CLI sandbox');

    // Real bundled fonts: `flutter test` draws text that names no family with the
    // Ahem font, every glyph a filled box.
    await loadFonts();
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);

    final progressFile = Platform.environment['FLUVIE_PROGRESS_FILE'];

    await renderVideo(
      video: target.$entry(),
      outDir: Directory(_outDir),
      compositionKey: _key.isEmpty ? 'render' : _key,
      frameCountOverride: _frames.isEmpty ? null : int.parse(_frames),
      cacheEnabled: !(bool.tryParse(_noCache) ?? false),
      aspect: parseAspect(_aspect),
      quality: parseQuality(_quality),
      export: parseExportFormat(_format),
      posterTime: parsePosterTime(_poster),
      defaultFontFamily: 'Roboto',
      setViewSize: (width, height) {
        tester.view.physicalSize = Size(width.toDouble(), height.toDouble());
        tester.view.devicePixelRatio = 1.0;
      },
      pumpWidget: tester.pumpWidget,
      pumpFrame: () => tester.pump(),
      runAsync: tester.runAsync,
      onProgress: progressFile == null || progressFile.isEmpty
          ? null
          : (completed, total) => writeRenderProgress(progressFile, completed, total),
      onCacheReport: (hits, total) => stdout.writeln('fluvie-capture: cache hits \$hits of \$total'),
    );
  }, timeout: $timeoutArg);
}
''';
}
