// #docregion imports
import 'package:flutter/material.dart' hide Animation, Image;
import 'package:fluvie/fluvie.dart';
import 'package:fluvie_ai/fluvie_ai.dart';
// #enddocregion imports
import 'package:fluvie_example/lessons/lesson.dart';

const _ink = Color(0xFF0B1020);
const _label = TextStyle(color: Colors.white, fontSize: 40, fontWeight: FontWeight.w600);

/// Lesson 13 — declare AI-generated media inline. Fluvie produces each asset
/// once before the frame loop, caches it in the project by a hash of the prompt,
/// and then paints it like a local file.
const lesson13GenerativeContent = Lesson(
  id: '13_generative_content',
  title: 'Generative content',
  intro:
      'Declare AI-generated media inline. Fluvie generates each asset once, '
      'caches it in the project by a hash of the prompt (plus an optional seed), '
      'and then treats it like a local file. Set your provider keys and install '
      'the generative resolver to render it.',
  video: lesson13Video,
);

/// Builds the lesson 13 composition: a generated image fills a 4 second square
/// scene while a label fades in. The image is produced and cached once, then
/// painted like a local asset on every later render.
Video lesson13Video() {
  return Video(
    size: VideoSize.square,
    poster: 1.seconds,
    scenes: [
      Scene(
        duration: 4.seconds,
        background: Background.color(_ink),
        children: [
          // #docregion image
          Positioned.fill(
            child: GenerativeImage.flux(
              prompt: 'a neon skyline at dusk, wide angle',
              fit: BoxFit.cover,
            ).animate([Animation.kenBurns(zoom: 1.2)]),
          ),
          // #enddocregion image
          Align(
            alignment: const Alignment(0, 0.78),
            child: const Text('Generated by AI', style: _label).animate([Animation.fadeIn()]),
          ),
        ],
      ),
    ],
  );
}

/// A generated video keeps its own audio (Veo 3 returns video with sound), so
/// picture and sound stay in sync because they are the same file. Drop it in a
/// scene's children like any clip.
// #docregion video
Widget generatedClip() => GenerativeVideo.veo(prompt: 'a man walking down the street', seconds: 6);
// #enddocregion video

/// Generated music feeds beat detection; generated speech mixes like a local
/// narration track. Both go in a scene's children and paint nothing themselves.
// #docregion audio
Widget generatedMusic() => GenerativeMusic.suno(prompt: 'lofi hip hop, 90bpm', seconds: 10);

Widget generatedNarration() => GenerativeSpeech.eleven(text: 'Welcome to Fluvie.', voice: 'rachel');
// #enddocregion audio
