/// Immutable document authoring, composition, and template API.
library;

export '../autoanimate/morph_preview.dart' show MorphPreview, showMorphPreview;
export '../autoanimate/pairing.dart'
    show SharedPair, SharedPairSource, SharedPairing, canonicalJson, pairElements;
export '../blocks/block_reflow.dart' show reflowedBlockTransforms;
export '../blocks/block_spec.dart' show BlockCrossAlign, BlockKind, BlockMainAlign, BlockSpec;
export '../capabilities/spec_capabilities.dart' show SpecCapabilities;
export '../document/deck_sections.dart' show DeckSection, deckSections;
export '../document/document_history.dart' show DocumentHistory;
export '../document/editor_command.dart'
    show
        AddAnimationCommand,
        AddAudioTrackCommand,
        AddEffectCommand,
        AddMediaEntryCommand,
        AddSceneCommand,
        AlignElementsCommand,
        ApplyAutoAnimateCommand,
        ApplyColourCommand,
        ApplyMasterCommand,
        ArrangeOrderCommand,
        ClearBlockCommand,
        DetachMasterCommand,
        DistributeElementsCommand,
        DuckAudioTracksCommand,
        EditorCommand,
        FillSlotCommand,
        GroupElementsCommand,
        InsertEffectStopCommand,
        InsertElementCommand,
        InsertElementsCommand,
        InsertKeyframeStopCommand,
        InsertTemplateSlideCommand,
        InsertTitleCommand,
        LinkSharedCommand,
        MakeBlockCommand,
        MakeOverlayCommand,
        MakeSceneLocalCommand,
        MoveElementToSceneCommand,
        MoveIntoGroupCommand,
        MoveOutOfGroupCommand,
        PasteEffectsCommand,
        RazorElementCommand,
        ReleaseFromBlockCommand,
        RemoveAnimationCommand,
        RemoveAudioTrackCommand,
        RemoveEffectCommand,
        RemoveEffectStopCommand,
        RemoveElementCommand,
        RemoveElementsCommand,
        RemoveKeyframeStopCommand,
        RemoveLaneCommand,
        RemoveMediaEntryCommand,
        RemoveSceneCommand,
        RenameThemeTokenCommand,
        ReorderAudioTrackCommand,
        ReorderEffectCommand,
        ReorderElementCommand,
        ReorderLaneCommand,
        ReorderSceneCommand,
        ReorderSceneRangeCommand,
        ReplaceElementCommand,
        ReplaceSharedMembersCommand,
        SequenceCommand,
        SetAnimationAnchorTriggerCommand,
        SetAnimationDelayCommand,
        SetAnimationDurationCommand,
        SetAnimationEaseCommand,
        SetAnimationTriggerCommand,
        SetAudioTrackCommand,
        SetBlockParamsCommand,
        SetDeckMetaCommand,
        SetEffectEnabledCommand,
        SetEffectParamCommand,
        SetEffectParamsCommand,
        SetEffectStopPositionsCommand,
        SetElementLaneCommand,
        SetElementMetaCommand,
        SetElementsMetaCommand,
        SetElementsVisibleCommand,
        SetKeyframeEasingCommand,
        SetKeyframePositionsCommand,
        SetKeyframeStopCommand,
        SetLaneCommand,
        SetMasterCommand,
        SetSceneMetaCommand,
        SetSceneNotesCommand,
        SetSceneStepsCommand,
        SetShowWindowCommand,
        SetStepNotesCommand,
        SetThemeCommand,
        SetTransformCommand,
        SetTransformsCommand,
        SplitSharedChainCommand,
        UngroupElementsCommand,
        UnlinkSharedCommand,
        UpdateMediaEntryCommand,
        UpdateSceneCommand,
        UpdateVideoCommand;
export '../document/editor_document.dart'
    show
        EditorDocument,
        EditorDocumentAnimations,
        EditorDocumentArrange,
        EditorDocumentAudio,
        EditorDocumentAutoAnimate,
        EditorDocumentAutoAnimateEdits,
        EditorDocumentBlocks,
        EditorDocumentEffects,
        EditorDocumentMasters,
        EditorDocumentMedia,
        EditorDocumentMeta,
        EditorDocumentMove,
        EditorDocumentMutations,
        EditorDocumentOverlays,
        EditorDocumentScenes,
        EditorDocumentSections,
        EditorDocumentTheme,
        MasterSlot;
export '../document/editor_document.dart' show EditorDocumentLanes, EditorDocumentShared;
export '../templates/template_merge.dart'
    show mergedMastersJson, mergedThemeJson, preparedTemplateScene;
