import 'dart:io';

import 'package:args/args.dart';
import 'package:fluvie_cli/src/cli_failure.dart';
import 'package:fluvie_cli/src/file_target.dart';
import 'package:fluvie_cli/src/preview_app.dart';
import 'package:fluvie_cli/src/process_runner.dart';
import 'package:fluvie_cli/src/project_assets.dart';

/// The CLI's own version, stamped into the preview app so a CLI upgrade
/// rebuilds it rather than reusing one generated by an older template.
const String previewCliVersion = '0.3.0';

/// The device `fluvie preview` runs on when none is given.
///
/// The host desktop, not the browser: a desktop preview decodes any clip through
/// ffmpeg, while the browser can only decode what WebCodecs supports (no ProRes,
/// which is the one format that carries alpha and passes the render probe). A
/// browser default would show a placeholder for exactly the compositions people
/// care most about.
String defaultPreviewDevice() {
  if (Platform.isLinux) return 'linux';
  if (Platform.isMacOS) return 'macos';
  if (Platform.isWindows) return 'windows';
  return 'chrome';
}

/// The platform directories the generated app needs for [device].
List<String> platformsFor(String device) => switch (device) {
  'chrome' || 'web-server' => const ['web'],
  'linux' => const ['linux'],
  'macos' => const ['macos'],
  'windows' => const ['windows'],
  // An unknown device is a real one (a phone, an emulator id), so scaffold the
  // mobile platforms and let `flutter run` do the matching.
  _ => const ['android', 'ios'],
};

/// `fluvie preview <file.dart>`: run a live, hot-reloading preview of a
/// composition.
///
/// The app it runs is generated and cached outside the project, so a project
/// stays a composition file, an `assets/` folder, and a pubspec. Editing the
/// composition hot-reloads the preview: the app path-depends on the project, so
/// `flutter run` tracks the file by its resolved path.
final class PreviewCommand {
  /// Creates the command; `runner` is injectable for tests.
  PreviewCommand({this._runner = const IoProcessRunner(), this._ensureApp = ensurePreviewApp});

  final ProcessRunner _runner;
  final Future<String> Function({
    required ProcessRunner runner,
    required FileTarget target,
    required List<String> platforms,
    required String cliVersion,
    required StringSink out,
    Map<String, String>? environment,
  })
  _ensureApp;

  /// The `preview` command's argument parser.
  static ArgParser buildParser() => ArgParser(usageLineLength: 80)
    ..addOption(
      'device',
      abbr: 'd',
      help: 'Device to run on (default: this desktop; "chrome" for the browser).',
    )
    ..addOption(
      'entry',
      defaultsTo: 'build',
      help: 'The top-level function returning the Video.',
    )
    ..addOption('project', help: 'The Fluvie project holding the composition.');

  /// Runs the command; returns the exit code (`0` ok, `64` usage, `1` failure).
  Future<int> execute(ArgResults args, {required StringSink out, required StringSink err}) async {
    if (args.rest.length != 1) {
      err.writeln('preview needs exactly one composition file.\n\n${buildParser().usage}');
      return 64;
    }
    final device = args.option('device') ?? defaultPreviewDevice();
    try {
      final target = resolveFileTarget(
        arg: args.rest.single,
        entry: args.option('entry') ?? 'build',
        project: args.option('project'),
      );
      syncAssetsBlock(target.projectDir);
      final appDir = await _ensureApp(
        runner: _runner,
        target: target,
        platforms: platformsFor(device),
        cliVersion: previewCliVersion,
        out: out,
      );
      out.writeln('Previewing ${args.rest.single} on $device. Press r to reload, q to quit.');
      // Inherited stdio: `flutter run` is interactive (r reloads, q quits), so it
      // takes over this terminal rather than being captured.
      final process = await Process.start(
        'flutter',
        [
          'run',
          '-d',
          device,
        ],
        workingDirectory: appDir,
        mode: ProcessStartMode.inheritStdio,
      );
      return process.exitCode;
    } on CliFailure catch (failure) {
      err.writeln(failure.message);
      return 1;
    } on ProcessException catch (error) {
      err.writeln(
        'Could not run "flutter" (${error.message}). Install Flutter and make '
        'sure `flutter` is on PATH (https://docs.flutter.dev/get-started/install).',
      );
      return 1;
    }
  }
}
